monitorv2 {
    output=DP-5
    bitdepth=10
    cm=auto
    mode=3840x2160@160.00Hz
    position=0x0
    scale=1.50
    sdrbrightness=1.5
    sdrsaturation=1.2
    vrr=3
}

monitorv2 {
    output=DP-4
    bitdepth=10
    cm=srgb
    mode=2560x1440@165.00Hz
    position=2560x0
    scale=1.0
    sdrbrightness=1.8
    sdrsaturation=.9
}

render {
    cm_auto_hdr=1
}
