monitorv2 {
    output=DP-5
    bitdepth=10
    cm=auto
    mode=3840x2160@160.00Hz
    position=0x0
    scale=1.50
    sdrbrightness=1.5
    sdrsaturation=1.2
    vrr=3
}

render {
    cm_auto_hdr=1
}

monitor = DP-4, disable
