monitorv2 {
    output=DP-4
    bitdepth=10
    cm=srgb
    mode=2560x1440@165.00Hz
    position=2560x0
    scale=1.0
    sdrbrightness=1.8
    sdrsaturation=.9
}

render {
    cm_auto_hdr=1
}

monitor = DP-5, disable
