# Set programs that you use
$browser = brave --enable-features=UseOzonePlatform --ozone-platform=wayland # platform: x11, wayland
$editor = alacritty -e ~/.scripts/tmux/sessionizer.sh
$terminal = alacritty
$fileManager = thunar
$menu = rofi -show drun

$waybar = killall waybar && waybar

bind = SUPER, return, exec, $terminal
bind = ALT, space, exec, $menu
bind = SUPER SHIFT, r, exec, $waybar


# application
bind = CONTROL ALT, w, exec, $browser
bind = CONTROL ALT, e, exec, $editor
bind = CONTROL ALT, d, exec, ~/.config/hypr/scripts/jump-to-existing.sh obsidian obsidian
bind = CONTROL ALT, m, exec, ~/.config/hypr/scripts/jump-to-existing.sh discord discord
bind = CONTROL ALT, g, exec, ~/.config/hypr/scripts/jump-to-existing.sh steam steam
