# Set programs that you use
$browser = brave --enable-features=UseOzonePlatform --ozone-platform=wayland # platform: x11, wayland
$editor = ghostty -e ~/.scripts/tmux/sessionizer.sh
$terminal = ghostty
$fileManager = thunar
$menu = rofi -show drun

$waybar = killall waybar && waybar

bind = SUPER, return, exec, $terminal
bind = ALT, space, exec, $menu

bind = SUPER SHIFT, r, exec, $waybar
bind = SUPER SHIFT, r, exec, ~/.config/hypr/scripts/set-random-wallpaper.sh


# application
bind = CONTROL ALT, w, exec, $browser
bind = CONTROL ALT, e, exec, $editor
bind = CONTROL ALT, d, exec, ~/.config/hypr/scripts/jump-to-existing.sh obsidian obsidian
bind = CONTROL ALT, m, exec, ~/.config/hypr/scripts/jump-to-existing.sh discord discord
bind = CONTROL ALT, g, exec, ~/.config/hypr/scripts/jump-to-existing.sh steam steam
bind = CONTROL ALT, p, exec, ~/.config/hypr/scripts/jump-to-existing.sh Bitwarden bitwarden-desktop
bind = CONTROL ALT, s, exec, ~/.config/hypr/scripts/jump-to-existing.sh com.stremio.stremio stremio 

#rofi
bind = SUPER, p, submap, superpsubmap
bind = SUPER, o, submap, searchsubmap

submap = superpsubmap
bind = , a,exec, /home/hain/.scripts/rofi/soundcard-choose
bind = , a, submap, reset
bind = SUPER, p,exec, /home/hain/.config/hypr/scripts/switch-monitor.sh
bind = SUPER, p, submap, reset
bind = , p,exec, /home/hain/.config/hypr/scripts/switch-monitor.sh
bind = , p, submap, reset
bind = ,escape,submap,reset 

bind = , q, exec, sleep 1 && hyprctl dispatch dpms off
bind = , q, submap, reset
bind = , o, exec, sleep 1 && hyprctl dispatch dpms on
bind = , o, submap, reset
bind = , l, exec, /home/hain/.scripts/rofi/toggle-llm
bind = , l, submap, reset
submap = reset

submap = searchsubmap 
bind = , o,exec, /home/hain/.scripts/rofi/rofi-search/search search
bind = , m, exec, /home/hain/.scripts/rofi/rofi-search/search quickmark
bind = ,escape,submap,reset 
submap = reset


bind = ,Print, exec, IMG=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%m-%s).png && grim -g "$(slurp)" $IMG && wl-copy < $IMG

