log:
  level: DEBUG

entryPoints:
  web:
    address: ':80/tcp'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443/tcp'
    http:
      middlewares:
        - compress@file
        - hsts@file
    http3: {}

api:
  dashboard: true
  insecure: true

providers:
  docker:
    watch: true
    network: traefik
    exposedByDefault: false
  file:
    filename: traefik_dynamic.yml

serversTransport:
  insecureSkipVerify: true


