tls:
  certificates:
    - certFile: /certs/local.crt
      keyFile:  /certs/local.key

http:
  routers:
    homeassistant-rtr:
      rule: "Host(`homeassistant.docker.local`)"
      entryPoints:
        - websecure 
      service: homeassistant-svc
    llm-rtr:
      rule: "Host(`llm.docker.local`)"
      entryPoints:
        - websecure 
      service: llm-svc
    wg-rtr:
      rule: "Host(`wg.docker.local`)"
      entryPoints:
        - websecure 
      service: wg-svc
  services:
    homeassistant-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.209.175:8123"
    llm-svc:
      loadBalancer:
        servers:
          - url: "http://main.local:8080"
    wg-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.209.175:51821"
