wallpaper {
    monitor = DP-5
    path = ~/Pictures/Wallpapers/current/wallpaper2.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = ~/Pictures/Wallpapers/current/wallpaper1.jpg
    fit_mode = cover
}
