windowrule {
    name = browser-window
    match:class = brave-browser
    workspace = 4
}

windowrule {
    name = alacritty
    match:class = Alacritty
    opacity=1
}


windowrule {
    name = bitwarden 
    match:class = Bitwarden
    workspace = 20
}



windowrule {
    name = note 
    match:class = obsidian
    workspace = 5
}

windowrule {
    name = stremio
    match:class = com.stremio.stremio
    workspace = 8
}

windowrule {
    name = steam
    match:class = steam
    center = on
    workspace = 9
}
