windowrule {
    name = browser-window
    match:class = brave-browser
    workspace = 4
}

windowrule {
    name = note 
    match:class = obsidian
    workspace = 5
}

windowrule {
    name = steam
    match:class = steam
    center = on
    workspace = 9
}
