# TODO: Run `cloudflared tunnel create hainhome` and `cloudflared tunnel credentials --json > ./credentials.yml`
# after this file will have:
# account-id: <YOUR_ACCOUNT_ID>
# tunnel-id: <YOUR_TUNNEL_ID>
# tunnel-secret: <YOUR_SECRET>
