services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - traefik
    environment:
      - TUNNEL_TOKEN=eyJhIjoiOGEwNzhlM2YwN2JjOTEzNmZjZTlhOTE0MjIwZWZkMzIiLCJ0IjoiZTEwZDNmNzItMWY3Mi00NTg4LWFiNTYtYjhmMTI5MTA4YTA0IiwicyI6IllXSmlNekF6TkRjdE5qTmxPQzAwTXpJNUxXRmpZV0l0WVRnNFpXSmlOVEF4TW1NeCJ9

networks:
  traefik:
    external: true
