#!/usr/bin/env zsh

function crop () {
    scrot -s -f ${NAME};
    xclip -selection clipboard -t image/png ${NAME};
}

function window () {
    scrot -u -f ${NAME};
    xclip -selection clipboard -t image/png ${NAME};
}

function all () {
        scrot -f ${NAME};
        xclip -selection clipboard -t image/png ${NAME};
}

function monitor () {
    scrot -f ${NAME};
    xclip -selection clipboard -t image/png ${NAME};
}


pid="/home/hain/.local/print-screen"
trap "rm -f $pid" SIGSEGV
trap "rm -f $pid" SIGINT

if [ -e $pid ]; then
    echo "already existed, exiting"
    exit # pid file exists, another instance is running, so now we politely exit
else
    echo $$ > $pid # pid file doesn't exit, create one and go on
fi

echo "start"

NAME=~/Pictures/Screenshots/$(date '+%m-%d-%Y_%H-%M-%S').png;
case "$1" in
    -c)
    crop
    ;;
    -w)
    window
    ;;
    -a)
        all
        ;;
    -m)
        monitor
        ;;
esac

rm -f $pid # remove pid file just before exiting
echo "removing"
exit
