#!/usr/bin/env zsh
set -euo pipefail

ID=$(xinput | grep -Po "Touchpad.*id=\K[0-9]*")
STATUS=$(xinput list-props "${ID}" | grep -Po "Device Enabled.*\K[0-9]")

if [ "$STATUS" = "1" ]
then
      xinput disable $ID
  else
      xinput enable $ID
fi
